In [2]:
%matplotlib inline
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using {device} device.")

Using cpu device.


In [4]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
            nn.ReLU()
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [5]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


In [7]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([7])


In [9]:
print(f"First Linear weights: {model.linear_relu_stack[0].weight}")
print(f"First Linear bias: {model.linear_relu_stack[0].bias}")

First Linear weights: Parameter containing:
tensor([[ 0.0194, -0.0270, -0.0115,  ...,  0.0004,  0.0002, -0.0165],
        [ 0.0279,  0.0348,  0.0092,  ...,  0.0270,  0.0071, -0.0130],
        [ 0.0215,  0.0118, -0.0100,  ..., -0.0033, -0.0173,  0.0179],
        ...,
        [-0.0274, -0.0195,  0.0099,  ...,  0.0280,  0.0345, -0.0177],
        [-0.0148, -0.0115, -0.0095,  ...,  0.0107,  0.0308,  0.0298],
        [-0.0352,  0.0059,  0.0068,  ..., -0.0061,  0.0183, -0.0301]],
       requires_grad=True)
First Linear bias: Parameter containing:
tensor([ 8.5315e-03,  1.2039e-02,  3.3523e-02,  6.7885e-03, -3.1905e-02,
         1.2577e-02,  2.8674e-02, -2.1631e-02,  3.4123e-02,  2.0768e-02,
        -7.6371e-03,  5.2883e-03,  2.3816e-02, -1.8611e-02, -9.9586e-03,
         1.0200e-02, -2.6447e-02, -2.6226e-02, -2.8981e-02, -1.9178e-02,
         3.3051e-02,  3.3091e-02, -3.4258e-02,  2.4287e-02, -3.3330e-02,
        -1.7082e-02, -2.4185e-02,  3.0944e-02, -3.4343e-02, -5.1196e-03,
         2.0588e

In [10]:
input_image = torch.rand(3, 28, 28)
print(input_image.size())

torch.Size([3, 28, 28])


In [11]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [12]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [13]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.1268, -0.4109,  0.1026,  0.0354, -0.3961,  0.9708, -1.0732, -0.1553,
         -0.3270, -0.0691,  0.4274, -0.7179, -0.2249,  0.3753,  0.1114, -0.0109,
          0.2810,  0.0681,  0.3944,  0.7126],
        [ 0.1987, -0.3817,  0.4069,  0.1651, -0.1994,  0.7672, -1.1217, -0.0476,
         -0.1003, -0.1507, -0.1249, -0.4749, -0.1602,  0.1294,  0.1653, -0.2578,
         -0.0104, -0.1848,  0.5645, -0.2163],
        [-0.0063, -0.1533,  0.1555,  0.1017, -0.2186,  0.6161, -0.9855, -0.0180,
         -0.1548, -0.0783,  0.3516, -0.5128,  0.2949,  0.3037,  0.0465, -0.3492,
          0.1735, -0.1883,  0.8476, -0.1377]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.0000, 0.1026, 0.0354, 0.0000, 0.9708, 0.0000, 0.0000, 0.0000,
         0.0000, 0.4274, 0.0000, 0.0000, 0.3753, 0.1114, 0.0000, 0.2810, 0.0681,
         0.3944, 0.7126],
        [0.1987, 0.0000, 0.4069, 0.1651, 0.0000, 0.7672, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.1294, 0.16

In [14]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)

In [15]:
print(logits)

tensor([[-4.2053e-01,  1.2883e-01,  2.4502e-01,  5.6018e-02, -3.8854e-02,
         -1.4776e-01,  2.2961e-01,  2.0153e-01, -1.7247e-01,  8.0072e-03],
        [-2.3116e-01,  2.4106e-01,  2.9364e-01,  2.0444e-04,  1.0850e-02,
         -1.4845e-01,  2.3614e-01,  1.5570e-01, -1.3716e-01, -2.5578e-02],
        [-3.7269e-01,  1.4558e-01,  3.1490e-01, -5.0411e-02, -4.6698e-02,
         -1.1032e-01,  3.7456e-01,  2.5320e-01, -2.5225e-01, -2.2954e-02]],
       grad_fn=<AddmmBackward0>)


In [16]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [17]:
print("Model structure: ", model, "\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size:{param.size()} | Values: {param[:2]}")

Model structure:  NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
) 


Layer: linear_relu_stack.0.weight | Size:torch.Size([512, 784]) | Values: tensor([[ 0.0194, -0.0270, -0.0115,  ...,  0.0004,  0.0002, -0.0165],
        [ 0.0279,  0.0348,  0.0092,  ...,  0.0270,  0.0071, -0.0130]],
       grad_fn=<SliceBackward0>)
Layer: linear_relu_stack.0.bias | Size:torch.Size([512]) | Values: tensor([0.0085, 0.0120], grad_fn=<SliceBackward0>)
Layer: linear_relu_stack.2.weight | Size:torch.Size([512, 512]) | Values: tensor([[ 0.0145, -0.0125, -0.0072,  ..., -0.0199, -0.0113, -0.0090],
        [ 0.0204,  0.0095,  0.0172,  ...,  0.0250,  0.0176,  0.0313]],
       grad_fn=<SliceBackward0>)
Layer: linear_relu_stack.2.bia